[versions]
    minecraft = '24w45a'
    quilt_mappings = "1.21+build.17"
    fabric-loader = "0.16.9"
    parchment = "2024.07.28"

    fabric = "0.107.3+1.21.4"

    terraformwoodapi = '12.0.0-alpha.1'

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }

    fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }

    terraformwoodapi = { module = 'com.terraformersmc.terraform-api:terraform-wood-api-v1', version.ref = 'terraformwoodapi' }
