[versions]
    minecraft = "23w14a"
    quilt_mappings = "23w13b+build.8"
    fabric-loader = "0.14.19"
    parchment = "2023.03.12"

    fabric = "0.77.1+1.20"

    clothconfig = "10.0.96"
    terraformwoodapi = "7.0.0-alpha.1"

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }
    fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader"}

    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }
    fabric_api_deprecated = { module = "net.fabricmc.fabric-api:fabric-api-deprecated", version.ref = "fabric" }

    clothconfig = { module = 'me.shedaniel.cloth:cloth-config-fabric', version.ref = 'clothconfig' }
    terraformwoodapi = { module = 'com.terraformersmc.terraform-api:terraform-wood-api-v1', version.ref = 'terraformwoodapi' }

[bundles]
    fabric = ["fabric_api", "fabric_api_deprecated"]
