[versions]
    minecraft = '23w05a'
    quilt_mappings = '23w05a+build.1'
    fabric-loader = "0.14.13"
    parchment = '2022.12.18'

    fabric = "0.73.3+1.19.4"

    clothconfig = '9.0.93'
    terraformwoodapi = '5.0.0-beta.1'

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }
    quilt_mappings = { module = 'org.quiltmc:quilt-mappings', version.ref = 'quilt_mappings' }
    fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader"}

    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }
    fabric_api_deprecated = { module = "net.fabricmc.fabric-api:fabric-api-deprecated", version.ref = "fabric" }

    clothconfig = { module = 'me.shedaniel.cloth:cloth-config-fabric', version.ref = 'clothconfig' }
    terraformwoodapi = { module = 'com.terraformersmc.terraform-api:terraform-wood-api-v1', version.ref = 'terraformwoodapi' }

[bundles]
    fabric = ["fabric_api", "fabric_api_deprecated"]
