[versions]
    minecraft = "1.19.4"
    quilt_mappings = "1.19.4+build.10"
    fabric-loader = "0.14.21"
    parchment = "2023.06.26"

    fabric = "0.85.0+1.19.4"

    terraformwoodapi = "6.1.2"

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }
    fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader"}

    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }
    fabric_api_deprecated = { module = "net.fabricmc.fabric-api:fabric-api-deprecated", version.ref = "fabric" }

    terraformwoodapi = { module = 'com.terraformersmc.terraform-api:terraform-wood-api-v1', version.ref = 'terraformwoodapi' }

[bundles]
    fabric = ["fabric_api", "fabric_api_deprecated"]
