[versions]
    minecraft = '1.19.3'
    quilt_mappings = '1.19.3+build.7'
    fabric-loader = "0.14.12"
    parchment = '2022.12.18'

    fabric = "0.70.0+1.19.3"

    artifice = '0.30.1+build.2-1.19'
    clothconfig = '9.0.93'
    terraformwoodapi = '5.0.0-beta.1'

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }
    quilt_mappings = { module = 'org.quiltmc:quilt-mappings', version.ref = 'quilt_mappings' }
    fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader"}

    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }
    fabric_api_deprecated = { module = "net.fabricmc.fabric-api:fabric-api-deprecated", version.ref = "fabric" }

    clothconfig = { module = 'me.shedaniel.cloth:cloth-config-fabric', version.ref = 'clothconfig' }
    artifice = { module = 'io.github.vampirestudios:artifice', version.ref = 'artifice' }
    terraformwoodapi = { module = 'com.terraformersmc.terraform-api:terraform-wood-api-v1', version.ref = 'terraformwoodapi' }

[plugins]
    quilt_loom = { id = "org.quiltmc.loom", version = "0.12.+" }

[bundles]
    fabric = ["fabric_api", "fabric_api_deprecated"]
