[versions]
    minecraft = "23w17a"
    quilt_mappings = "23w16a+build.1"
    fabric_mappings = "23w17a+build.10"
    fabric-loader = "0.14.19"
    parchment = "2023.03.12"

    fabric = "0.80.0+1.20"

    terraformwoodapi = '7.0.0-alpha.5'

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }
    fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader"}

    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }
    fabric_api_deprecated = { module = "net.fabricmc.fabric-api:fabric-api-deprecated", version.ref = "fabric" }

    terraformwoodapi = { module = 'com.terraformersmc.terraform-api:terraform-wood-api-v1', version.ref = 'terraformwoodapi' }

[bundles]
    fabric = ["fabric_api", "fabric_api_deprecated"]
