[versions]
    minecraft = '1.19.3'
    quilt_mappings = '1.19.3+build.1'
    loader_version='0.14.11'
    parchment = '2022.08.14'

    fabric = "0.68.1+1.19.3"

    clothconfig = '9.0.93'
    terraformwoodapi = '5.0.0-beta.1'

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }
    quilt_mappings = { module = 'org.quiltmc:quilt-mappings', version.ref = 'quilt_mappings' }
    fabric_loader = { module = 'net.fabricmc:fabric-loader', version.ref = 'loader_version' }

    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }
    fabric_api_deprecated = { module = "net.fabricmc.fabric-api:fabric-api-deprecated", version.ref = "fabric" }

    clothconfig = { module = 'me.shedaniel.cloth:cloth-config-fabric', version.ref = 'clothconfig' }
    terraformwoodapi = { module = 'com.terraformersmc.terraform-api:terraform-wood-api-v1', version.ref = 'terraformwoodapi' }

[plugins]
    quilt_loom = { id = "org.quiltmc.loom", version = "1.0.+" }

[bundles]
    fabric = ["fabric_api", "fabric_api_deprecated"]
