name: On Push

on:
  push:
    branches: [ master, dev/1.17-snapshots ]

jobs:
  build_run_publish_everywhere:
    name: Run tests for ${{ matrix.minecraftVersion }} and Release
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[Release]')"
    strategy:
      fail-fast: false
      matrix:
        minecraftVersion:
          - 1.16.5
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: Geometrically/fabric-test-runner@v1
        id: testRunner
        with:
          minecraftVersion: ${{ matrix.minecraftVersion }}
      - name: Upload to Bintray, GitHub and CurseForge and Modrinth
        run: ./gradlew clean bintrayUpload github curseforge publishModrinth
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          BINTRAY_USER: oliviathevampire
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}